# Generated by Django 4.0 on 2021-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_review_delete_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.CharField(max_length=10),
        ),
    ]
