# Generated by Django 4.0 on 2021-12-22 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_alter_review_rating_alter_videogame_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added to organizer'),
            preserve_default=False,
        ),
    ]
