# Generated by Django 4.0 on 2021-12-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_videogame_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='pub_date',
        ),
    ]
