# Generated by Django 4.0 on 2021-12-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_remove_videogame_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='game_console',
            field=models.CharField(default='Switch', max_length=50),
        ),
    ]
