# Generated by Django 4.0 on 2021-12-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_alter_videogame_game_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='developer',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
