# Generated by Django 4.0 on 2021-12-28 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_videogame_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 16, 19, 32, 635285, tzinfo=utc), verbose_name='date added to organizer'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.CharField(default='yyyy/mm/dd', max_length=10),
        ),
    ]
