# Generated by Django 4.0 on 2021-12-28 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_videogame_pub_date_alter_videogame_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added to organizer'),
        ),
    ]
