# Generated by Django 4.0 on 2022-01-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_alter_videogame_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='publisher',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.CharField(default='yyyy', max_length=10),
        ),
    ]
