# Generated by Django 4.0 on 2022-01-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_alter_videogame_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
