# Generated by Django 4.0 on 2022-01-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_alter_videogame_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.CharField(default='yyyy', max_length=4),
        ),
    ]
